### ISSUE TITLE
Handle custom port for SSH target

### ISSUE THREAD

**Issue by mjtko** [alces-software/flight-terminal-service#2]
As well as being able to specify the hostname, we need to be able to specify the port number to connect to in case the SSH service isn't configured to listen on the default, port 22.

Don't mind if this is implemented as a separate (optional) field (default to port 22 if no value is set), or as an updated interpretation of the hostname when specified as `host:port` (should also default to port 22 if no colon-delimited port-part is specified).

**Comment by benarmston** [comment]
This has been implemented as an "updated interpretation of the hostname when specified as `host:port` (defaulting to port 22 if no colon-delimited port-part is specified)".
